name: output-event
on: issues
jobs:
  output-event:
    runs-on: ubuntu-latest
    steps:
      - name: Get-Code
        uses: actions/checkout@v3
      - name: Install-Dependencies
        run: npm ci
      - name: Output-Event
        run: echo "${{ toJson(github.event)}}"
